pipeline{
    agent {
        label 'DevServer'
    }
    tools {
        maven 'maven'
        git 'git'
    }
    parameters {
    string defaultValue: 'sivanagireddy', name: 'FirstName'
    }

    environment{
        NAME = "NagiReddy"
    }
    stages{
        stage('Build'){
            steps{
                sh "mvn clean package"
                echo "Hello, $NAME ${params.FirstName}" 
            }
            post {
            success {
                archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }
        
    }
}
