pipeline{
    agent {
        label 'DevServer'
    }
    tools {
        maven 'maven'
        git 'git'
    }
    parameters {
    string defaultValue: 'sivanagireddy', name: 'FirstName'
    }

    envronment{
        NAME = "NagiReddy"
    }
    stages{
        stage('Build'){
            steps{
                sh "mvn clean package"
                echo "Hello, $NAME ${params.FirstName}" 
            }
            
        }
        stage('test'){
            parallel {
                stage(testA){
                    steps {
                        echo 'it is testA'
                    }
                }
                stage(testB){
                    steps{
                        echo "this is testB"
                    }
                }
            }
            post {
            success {
                archiveArtifacts artifacts: '**/target/*.jar'
                }
            }
        }
        
    }
}
